version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: 'java-postgres'
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=1111'
      - 'POSTGRES_DB=WebMarketplace_db'
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data



  app:
    build: ./
    container_name: 'java-app'
    ports:
      - "1000:1000"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/WebMarketplace_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1111
    depends_on:
      - postgres
volumes:
  postgres-data:




